#ifndef GAME_CONSTANTS_H
#define GAME_CONSTANTS_H

#define MAX_PLAYERS 4
#define DEFAULT_PLAYER_COUNT 2

#define PLAYER_COLLIDER_WIDTH 72.0f
#define PLAYER_COLLIDER_HEIGHT 120.0f
#define PLAYER_VISUAL_HEIGHT_SCALE 1.5f

#endif
